### ISSUE TITLE
spring Consul Config Key/Value

### ISSUE THREAD

**Issue by famousmighodaro** [Book-Microservices-v2/chapter08c#2]
Is there a way to store the key/value because whenever consul is shutdown  and restart again, all config data are lost. It does not persist.

**Comment by mechero** [comment]
Hi! I'm a bit late to this, probably you found the answer already. The way the configuration is persisted in the book's use case is by loading a previously exported data file into Consul. In a production setup, you can follow Consul's docs to find out what persistence options there are.
