### ISSUE TITLE
Centralized config on Consul ignored

### ISSUE THREAD

**Issue by wagenbm** [Book-Microservices-v2/chapter08c#3]
I have a similar problem like andreykirson: The configuration I maintained on Consul is ignored and not applied.

I did the following:

**bootstrap.properties:**

spring.application.name=multiplication
spring.cloud.consul.config.enabled=true
spring.cloud.consul.config.prefix=config
spring.cloud.consul.config.format=yaml
spring.cloud.consul.config.default-context=defaults
spring.cloud.consul.config.data-key=application.yml

**application.properties:**

spring.application.name=multiplication
spring.cloud.bootstrap.enabled=true
spring.config.import=consul:
server.error.include-message=always
server.error.include-binding-errors=always

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:~/multiplication;DB_CLOSE_ON_EXIT=false
spring.jpa.hibernate.ddl-auto=update

amqp.exchange.attempts=attempts.topic

logging.level.org.springframework.amqp.rabbit.core.RabbitAdmin = DEBUG

**This is my folder structure at Consul:**

![image](https://github.com/Book-Microservices-v2/chapter08c/assets/45208235/bb783cda-c219-48be-a1eb-fadb9405fa65)

**I am starting the application using this command:**

./mvnw spring-boot:run "-Dspring-boot.run.arguments=--spring.profiles.active=multiplication,production"

I see the following line in the logs:

2023-08-05T12:43:53.643+02:00  INFO 13804 --- [           main] m.b.m.MultiplicationApplication          : The following 2 profiles are active: "multiplication", "production"

However, this log line does not show-up at all:

b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource ...

Why is this log-line not showing up?

I already checked the documentation and do not see what I am missing.

**Comment by wagenbm** [comment]
Update:

I changed in application.properties the line

spring.config.import=consul:

to

spring.config.import=consul:8500

This caused the following log:

org.springframework.boot.context.config.ConfigDataResourceNotFoundException: Config data resource '[ConsulConfigDataResource@1e7aa82b context = 'config/multiplication,production/', optional = true, properties = [ConsulConfigProperties@3b2c0e88 enabled = true, prefixes = list['config'], defaultContext = 'application', profileSeparator = ',', format = KEY_VALUE, dataKey = 'data', aclToken = [null], watch = [ConsulConfigProperties.Watch@5bd82fed waitTime = 55, 
enabled = true, delay = 1000], failFast = true, name = 'multiplication'], profile = 'production']' via location 'consul:8500' cannot be found

Why is the defaultContext 'application' and not 'default'?
Why ist the dataKey 'data' and not 'application.yml'?

**Comment by mechero** [comment]
Do you use the same versions of Spring Boot, Cloud as in the book? Otherwise, there might have been changes in the configuration. For example, `bootstrap.properties` is no longer used. 

Check [this article](https://thepracticaldeveloper.com/book-update-2.7.1/) in case it helps. And the related repository. It's a book upgrade to the latest version.

**Comment by wagenbm** [comment]
Thanks a lot, that helped!
